# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
    - step:
        name: Deploy to test
        deployment: test
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
         - pipe: atlassian/ftp-deploy:0.2.0
           variables:
              USER: pinetree-devwin\kooco_admin2
              PASSWORD: Koo29152407co
              SERVER: ftp://waws-prod-hk1-009.ftp.azurewebsites.windows.net
              REMOTE_PATH: /site/wwwroot
